### ISSUE TITLE
cmsplugin_filer_html5video

### ISSUE THREAD

**Issue by superrandres** [beniwohli/cmsplugin-filer-html5video#4]
ImportError: cannot import name 'FILER_STATICMEDIA_PREFIX'

**Comment by TheDeadOne** [comment]
I've got the same error.

Python 2.7.10
Django 1.9.7
django-cms 3.3.0
django-filer 1.2.2
cmsplugin-filer 1.1.1
cmsplugin-filer-html5video 0.1

```
Traceback (most recent call last):
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\utils\autoreload.py",
 line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\core\management\comma
nds\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\utils\autoreload.py",
 line 249, in raise_last_exception
    six.reraise(*_exception)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\utils\autoreload.py",
 line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\__init__.py", line 18
, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\apps\registry.py", li
ne 115, in populate
    app_config.ready()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\contrib\admin\apps.py
", line 22, in ready
    self.module.autodiscover()
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\contrib\admin\__init_
_.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "D:\Projects\evrysoft\env2\lib\site-packages\django\utils\module_loading.
py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "c:\Python\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\admin\__init__.py", line
 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\plugin_pool.py", line 32
, in discover_plugins
    load('cms_plugins')
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\utils\django_load.py", l
ine 57, in load
    get_module(app, modname, verbose, failfast)
  File "D:\Projects\evrysoft\env2\lib\site-packages\cms\utils\django_load.py", l
ine 41, in get_module
    module = import_module(module_name)
  File "c:\Python\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Projects\evrysoft\env2\lib\site-packages\cmsplugin_filer_html5video\c
ms_plugins.py", line 9, in <module>
    from filer.settings import FILER_STATICMEDIA_PREFIX
ImportError: cannot import name FILER_STATICMEDIA_PREFIX
```
